Repository Medology/behat-google-place-autocomplete, pull requests merged in 2021-07, with the labels that each got.

#54 Update minor version of PHP to get latest security updates
  bin/lib/images.sh
Labels: No QA, ✓ Review

#55 Update minor version of PHP to get latest security updates
  bin/lib/images.sh
Labels: No QA

#60 Fixing CircleCI
  .circleci/config.yml
Labels: ❐ Review

#63 Merge with branch 1.0
  .circleci/config.yml
Labels: Do Not Review
